notifications:
  webhooks:
    - https://webhook.commit-email.info/
dist: xenial
addons:
  apt:
    packages:
      - libreoffice
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
before_script:
  - unset BUNDLE_GEMFILE
script:
  - rake
