# -*- mode: ruby; coding: utf-8 -*-
#
# Copyright (C) 2014-2019  Kouhei Sutou <kou@clear-code.com>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

source "https://rubygems.org/"

gemspec

base_dir = File.dirname(__FILE__)

general = "chupa-text-decomposer-libreoffice-general"
gem general, path: File.join(base_dir, "..", general)

local_gem_names = [
  "chupa-text",
  "chupa-text-decomposer-pdf",
]
local_gem_names.each do |name|
  local_dir = File.join(base_dir, "..", "..", name)
  if File.exist?(local_dir)
    gem name, :path => local_dir
  end
end
